version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: bienesraices_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      # Puedes montar un archivo SQL similar para MySQL si lo deseas
      # - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  adminer:
    image: adminer
    ports:
      - "8080:8080"